apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: helloworld
  name: helloworld-rest-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: helloworld
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helloworld
    spec:
      containers:
      - name: helloworld-rest-app
        image: vpec1/helloworld-rest-app:latest
        imagePullPolicy: "Always" # Force latest image pull
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
